[package]
name = "backtrack"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["TheLukeGuy"]
license = "Apache-2.0"
description = "Get the current compiler version on any version."
repository = "https://github.com/TheLukeGuy/backtrack"
keywords = ["version", "compiler", "backward", "compatibility", "old", "sys"]
