name: Test
on: [pull_request, push]
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Rust caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: tests/executor
      - name: Build test executor
        run: cargo build --release
        working-directory: tests/executor
      - name: Extract compilers
        run: >-
          tests/executor/target/release/backtrack-test-executor
          extract-compilers
      - name: Install fonts
        run: |
          brew tap homebrew/cask-fonts
          brew install font-libertinus
      - name: Run tests
        run: tests/executor/target/release/backtrack-test-executor test
